---
- name: repository | RedHat/CentOS | Add GitLab runner repository
  ansible.builtin.template:
    src: "repository/rpm.j2"
    dest: "/etc/yum.repos.d/gitlab-runner.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_os_family == "RedHat"

- name: repository | RedHat/CentOS | Add GitLab runner repository keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ gitlab_runner_repository_key }}"
    - "{{ gitlab_runner_repository_key_pub }}"
  register: gitlab_runner_repository_state
  when: ansible_os_family == "RedHat"

- name: repository | RedHat/CentOS | Refresh yum metadata cache if repository changed
  ansible.builtin.command: yum clean metadata
  when:
    - gitlab_runner_repository_state.changed
    - ansible_os_family == "RedHat"
  # Data should be refreshed immediatly for other roles which depend on them
  # Flush handlers is not used because it would potentially flush handlers,
  # which are not meant to be flushed at this poiunt in the playbook
  tags:
    - skip_ansible_lint

- name: repository | Debian/Ubuntu | Add GitLab runner repository key
  ansible.builtin.apt_key:
    url: "{{ gitlab_runner_repository_key }}"
    state: present
  when: ansible_os_family == "Debian"

- name: repository | Debian/Ubuntu | Add GitLab runner repository
  ansible.builtin.template:
    src: "repository/deb.j2"
    dest: "/etc/apt/sources.list.d/gitlab-runner.list"
    owner: "root"
    group: "root"
    mode: "0644"
  register: gitlab_runner_repository_state
  when: ansible_os_family == "Debian"

- name: repository | Debian/Ubuntu | Update repository cache if repository changed
  ansible.builtin.apt:
    update_cache: true
  when:
    - gitlab_runner_repository_state.changed
    - ansible_os_family == "Debian"
  # Data should be refreshed immediatly for other roles which depend on them
  # Flush handlers is not used because it would potentially flush handlers,
  # which are not meant to be flushed at this poiunt in the playbook
  tags:
    - skip_ansible_lint
