---
- name: runner-install | create gitlab-runner group
  ansible.builtin.group:
    name: "{{ gitlab_runner_group }}"
    gid: "{{ gitlab_runner_group_gid }}"
    state: present
  when: gitlab_runner_user_enable | bool

- name: runner-install | create gitlab-runner user
  ansible.builtin.user:
    name: "{{ gitlab_runner_user }}"
    uid: "{{ gitlab_runner_user_uid }}"
    group: "{{ gitlab_runner_group }}"
    home: "/home/{{ gitlab_runner_user }}"
    shell: "/bin/bash"
    comment: gitlab-runner
  when: gitlab_runner_user_enable | bool

- name: runner-install | Install gitlab-runner dependencies
  ansible.builtin.package:
    name: "{{ gitlab_runner_package_dependencies }}"
    state: present
    update_cache: true

- name: runner-install | Install gitlab-runner
  ansible.builtin.package:
    name: "{{ gitlab_runner_package }}"
    state: present
